### ISSUE TITLE
Extremely rare crash in yakui examples when resizing window

### ISSUE THREAD

**Issue by msparkles** [SecondHalfGames/yakui#181]
```
[2024-07-17T12:27:29Z ERROR wgpu::backend::wgpu_core] Handling wgpu errors as fatal by default
thread 'main' panicked at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:2996:5:
wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `Render Encoder`
    In a pass parameter
      note: command buffer = `Render Encoder`
    Attachments have differing sizes: the color attachment at index 0's texture view has extent (801, 600, 1) but is followed by the color attachment at index 0's resolve texture view which has (800, 600, 1)


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/vulkan/instance.rs:186:58:
Trying to destroy a SurfaceSemaphores that is still in use by a SurfaceTexture
stack backtrace:
   0:     0x5db69e86b025 - std::backtrace_rs::backtrace::libunwind::trace::h1a07e5dba0da0cd2
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x5db69e86b025 - std::backtrace_rs::backtrace::trace_unsynchronized::h61b9b8394328c0bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5db69e86b025 - std::sys_common::backtrace::_print_fmt::h1c5e18b460934cff
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5db69e86b025 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e1a1972118942ad
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5db69e894a1b - core::fmt::rt::Argument::fmt::h07af2b4071d536cd
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/rt.rs:165:63
   5:     0x5db69e894a1b - core::fmt::write::hc090a2ffd6b28c4a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/fmt/mod.rs:1157:21
   6:     0x5db69e8682af - std::io::Write::write_fmt::h8898bac6ff039a23
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/io/mod.rs:1832:15
   7:     0x5db69e86adfe - std::sys_common::backtrace::_print::h4e80c5803d4ee35b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5db69e86adfe - std::sys_common::backtrace::print::ha96650907276675e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5db69e86c269 - std::panicking::default_hook::{{closure}}::h215c2a0a8346e0e0
  10:     0x5db69e86bfad - std::panicking::default_hook::h207342be97478370
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:298:9
  11:     0x5db69e86c703 - std::panicking::rust_panic_with_hook::hac8bdceee1e4fe2c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:795:13
  12:     0x5db69e86c5e4 - std::panicking::begin_panic_handler::{{closure}}::h00d785e82757ce3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
  13:     0x5db69e86b4e9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1628d957bcd06996
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x5db69e86c317 - rust_begin_unwind
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
  15:     0x5db69cdd0ed3 - core::panicking::panic_fmt::hdc63834ffaaefae5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
  16:     0x5db69e8927ec - core::panicking::panic_display::h57ec0894e5f003fc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:263:5
  17:     0x5db69cdd0e9c - core::option::expect_failed::h7f842a57ad883afa
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:1994:5
  18:     0x5db69dad30ea - core::option::Option<T>::expect::hb9486f1caa00435c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:895:21
  19:     0x5db69da3f633 - wgpu_hal::vulkan::instance::<impl wgpu_hal::vulkan::Swapchain>::release_resources::hc1a440838368a41e
                               at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/vulkan/instance.rs:186:31
  20:     0x5db69da4507a - wgpu_hal::vulkan::instance::<impl wgpu_hal::Surface for wgpu_hal::vulkan::Surface>::unconfigure::h80652238a898e866
                               at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/vulkan/instance.rs:988:38
  21:     0x5db69d8fa935 - wgpu_core::hub::Hub<A>::clear::hc304f1e1829e5b4a
                               at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/hub.rs:246:29
  22:     0x5db69d94268c - <wgpu_core::global::Global as core::ops::drop::Drop>::drop::he6587eb871b8bcfb
                               at /mnt/cum/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-core-0.21.1/src/global.rs:140:13
  23:     0x5db69d551567 - core::ptr::drop_in_place<wgpu_core::global::Global>::hfdec84bd4875f30e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  24:     0x5db69d552674 - core::ptr::drop_in_place<wgpu::backend::wgpu_core::ContextWgpuCore>::h123dafb3c0a7a02d
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  25:     0x5db69d551ef0 - core::ptr::drop_in_place<dyn wgpu::context::DynContext>::h42f779b290691424
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  26:     0x5db69d47eb6a - alloc::sync::Arc<T,A>::drop_slow::h7490d464c6d661f6
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/sync.rs:1812:18
  27:     0x5db69d4833c0 - <alloc::sync::Arc<T,A> as core::ops::drop::Drop>::drop::h474b2d39794d7b4c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/sync.rs:2470:13
  28:     0x5db69d5541fb - core::ptr::drop_in_place<alloc::sync::Arc<dyn wgpu::context::DynContext>>::h144a816af6c7ff3c
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  29:     0x5db69d550a07 - core::ptr::drop_in_place<wgpu::Buffer>::hb55b0ceebb9ef9dc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  30:     0x5db69d45cdf6 - core::ptr::drop_in_place<core::option::Option<wgpu::Buffer>>::h7b39062fce0e384a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  31:     0x5db69d45ccec - core::ptr::drop_in_place<yakui_wgpu::buffer::Buffer>::h52a72d46d940398e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  32:     0x5db69cdddbbc - core::ptr::drop_in_place<yakui_wgpu::YakuiWgpu>::h6fc5dfb7fd945f8b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  33:     0x5db69cddd922 - core::ptr::drop_in_place<yakui_app::Graphics>::h6bc918468e7208ac
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  34:     0x5db69cddeacb - core::ptr::drop_in_place<core::option::Option<yakui_app::Graphics>>::h192ff4c72701c64b
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  35:     0x5db69cdde20a - core::ptr::drop_in_place<bootstrap::App<fn()>>::h8c3cff43a7902931
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ptr/mod.rs:514:1
  36:     0x5db69cde7936 - bootstrap::run::h2670dbb09715a839
                               at /home/madeline/yakui/crates/bootstrap/src/lib.rs:269:1
  37:     0x5db69cde7b89 - bootstrap::start::h97b6e9a5d8d13f67
                               at /home/madeline/yakui/crates/bootstrap/src/lib.rs:218:5
  38:     0x5db69cdda5dd - text_render::main::hc418a7393f318cee
                               at /home/madeline/yakui/crates/yakui/examples/text_render.rs:72:5
  39:     0x5db69cddb2db - core::ops::function::FnOnce::call_once::h8cb488293071c5bc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  40:     0x5db69ce5a63e - std::sys_common::backtrace::__rust_begin_short_backtrace::hbae0e8da5a6e3dbc
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  41:     0x5db69ce57ba1 - std::rt::lang_start::{{closure}}::h38f87a66b8a3f613
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:159:18
  42:     0x5db69e860390 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6abeee5a7794ceb5
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:284:13
  43:     0x5db69e860390 - std::panicking::try::do_call::hd6e966bb06877057
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  44:     0x5db69e860390 - std::panicking::try::hc9b3807f5768cb19
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  45:     0x5db69e860390 - std::panic::catch_unwind::h94a757c154076c6e
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  46:     0x5db69e860390 - std::rt::lang_start_internal::{{closure}}::hc5223fb36050c743
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:48
  47:     0x5db69e860390 - std::panicking::try::do_call::hddf7b4e1ebeb3f69
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  48:     0x5db69e860390 - std::panicking::try::h1842860a1f941a31
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  49:     0x5db69e860390 - std::panic::catch_unwind::h009016ccf811d4c3
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  50:     0x5db69e860390 - std::rt::lang_start_internal::h3ed4fe7b2f419135
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:141:20
  51:     0x5db69ce57b7a - std::rt::lang_start::h2217c881075a117a
                               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/rt.rs:158:17
  52:     0x5db69cdda65e - main
  53:     0x7e6e8984fc88 - <unknown>
  54:     0x7e6e8984fd4c - __libc_start_main
  55:     0x5db69cdd1905 - _start
  56:                0x0 - <unknown>
```

**Comment by LPGhatguy** [comment]
Is this still happening? If so, let's reopen this issue. Otherwise, the winit code has shifted around a fair bit and I haven't been able to repro this!
